query AllAuctions($options: PagePaginationInput) {
  getAllAuctions(options: $options) {
    count
    pages
    results {
      itemCount
      name
      startDate
      visible
      id
    }
  }
}
